# 修改前缀键为 Ctrl+s
unbind C-b
set -g prefix C-s
bind C-s send-prefix

# Alt 快捷键无延迟
set -s escape-time 0

# 启用鼠标支持
set -g mouse on

# 终端配置合并 + 真彩色支持
set -g terminal-overrides "xterm*:smcup@:rmcup@,xterm-256color:Tc"

# 状态栏颜色
set -g status-bg colour234
set -g status-fg colour15

# 左侧显示会话名
set -g status-left '#[fg=colour82,bold]#S '

# 右侧显示时间
set -g status-right '#[fg=colour238,bold]%Y-%m-%d #[fg=colour15,bold]%H:%M'

# 窗口列表选中颜色
setw -g window-status-current-style bg=colour236,fg=colour82

# 状态栏刷新间隔
set -g status-interval 1

# 面板边框颜色
set -g pane-border-style fg=green
set -g pane-active-border-style fg=red

# Alt+方向键 无缝切换面板
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Alt+数字 快速切换窗口
bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4

# 窗口/面板索引从 1 开始
set -g base-index 1
setw -g pane-base-index 1

# 重命名窗口快捷键
bind , command-prompt -p "rename window:" "rename-window '%%'"

# 重载 tmux 配置快捷键 r
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# 多面板同步输入 g
bind g setw synchronize-panes

# 终端历史记录行数
set -g history-limit 10000

# ========== 复制粘贴 系统剪贴板互通 ==========
set -g mode-keys vi
bind -n M-v copy-mode

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "~/.config/tmux/scripts/copy_to_clipboard.sh"
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "~/.config/tmux/scripts/copy-pipe-and-cancel"

# Ctrl+Shift+V 粘贴
bind -n C-S-v run -b "~/.config/tmux/scripts/paste_from_clipboard.sh"
bind -T copy-mode-vi C-S-v send-keys -X cancel \; run -b "~/.config/tmux/scripts/paste_from_clipboard.sh"
bind -T copy-mode C-S-v send-keys -X cancel \; run -b "~/.config/tmux/scripts/paste_from_clipboard.sh"

# Alt+Shift+V 粘贴
bind -n M-V run -b "~/.config/tmux/scripts/paste_from_clipboard.sh"
bind -T copy-mode-vi M-V send-keys -X cancel \; run -b "~/.config/tmux/scripts/paste_from_clipboard.sh"
bind -T copy-mode M-V send-keys -X cancel \; run -b "~/.config/tmux/scripts/paste_from_clipboard.sh"

# ========== 你指定要的核心功能 ==========
# Alt+q 关闭当前面板
bind -n M-q kill-pane

# Alt + d 直接退出/分离当前会话
bind -n M-d detach-client

# 会话退出不销毁、后台保持
set -g detach-on-destroy off

# 关闭窗口自动重排编号
set -g renumber-windows on
setw -g automatic-rename on

# ========== TPM 会话保存插件 ==========
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-processes 'script lazygit yazi'
set -g @continuum-save-interval '5'
set -g @continuum-restore 'off'

# TPM 初始化必须放在最后一行
run '~/.tmux/plugins/tpm/tpm'

